from __future__ import annotations

import subprocess
import tempfile
import unittest
from pathlib import Path

from engine.provider_runtime import (
    CommandResult,
    ProviderHealth,
    ProviderTaskRequest,
    SubprocessRunner,
    TelemetryEvent,
    execute_provider_task,
    select_runtime_provider,
    validate_allowed_commands,
    validate_changed_paths,
    validate_runtime_scopes,
)
from engine.providers.antigravity import AntigravityAdapter
from engine.work_orchestrator import WorkItem


class EditingRunner:
    def __init__(self, relative_path: str, *, git_mutation=None) -> None:
        self.relative_path = relative_path
        self.git_mutation = git_mutation
        self.subprocess = SubprocessRunner()

    def run(self, invocation):
        if invocation.provider_id == "git-runtime":
            return self.subprocess.run(invocation)
        target = invocation.cwd / self.relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("generated by provider\n", encoding="utf-8")
        if self.git_mutation:
            self.git_mutation(invocation.cwd)
        return CommandResult(
            returncode=0,
            stdout='{"conversation_id":"test","status":"SUCCESS","response":"done","usage":{}}',
            stderr="",
        )


def initialize_repository(root: Path, *, with_remote: bool = True) -> tuple[Path, Path | None]:
    bare = root / "remote.git" if with_remote else None
    repo = root / "repo"
    if bare:
        subprocess.run(["git", "init", "--bare", str(bare)], check=True, capture_output=True)
    subprocess.run(["git", "init", "-b", "main", str(repo)], check=True, capture_output=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "Factory Test"], check=True)
    subprocess.run(
        ["git", "-C", str(repo), "config", "user.email", "factory@example.invalid"],
        check=True,
    )
    (repo / "README.md").write_text("base\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "README.md"], check=True)
    subprocess.run(
        ["git", "-C", str(repo), "commit", "-m", "base"],
        check=True,
        capture_output=True,
    )
    if bare:
        subprocess.run(
            ["git", "-C", str(repo), "remote", "add", "origin", str(bare)],
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(repo), "push", "-u", "origin", "main"],
            check=True,
            capture_output=True,
        )
    return repo, bare


def request_for(repo: Path, task: str, path: str) -> ProviderTaskRequest:
    return ProviderTaskRequest.from_mapping({
        "run_id": "test",
        "task_id": task,
        "repository": "owner/repo",
        "worktree": str(repo),
        "integration_branch": "factory/test",
        "target_branch": "main",
        "working_branch": f"factory/test/{task}",
        "paths": [path],
        "instruction": "Create result documentation.",
    })


class ProviderRuntimeTests(unittest.TestCase):
    def test_runtime_scopes_fail_closed_for_wildcard_parent_and_protected_paths(self) -> None:
        for paths in ([], ["*"], [".github/workflows"], ["infra"], ["infra/factory"]):
            with self.subTest(paths=paths), self.assertRaises(ValueError):
                validate_runtime_scopes(paths)
        self.assertEqual(validate_runtime_scopes(["docs/feature"]), ("docs/feature",))

    def test_changed_paths_must_stay_inside_declared_scope(self) -> None:
        self.assertEqual(
            validate_changed_paths(["docs/a/result.md"], ["docs/a"]),
            ("docs/a/result.md",),
        )
        with self.assertRaisesRegex(ValueError, "outside declared scope"):
            validate_changed_paths(["src/escape.py"], ["docs/a"])

    def test_unsafe_command_patterns_are_rejected(self) -> None:
        for command in (
            "git push origin main",
            "git status",
            "rm -rf .",
            "npm test && curl bad",
            "python -c print(1)",
            "npm test > output.txt",
        ):
            with self.subTest(command=command), self.assertRaises(ValueError):
                validate_allowed_commands([command])

    def test_request_requires_array_fields_and_strict_remote_name(self) -> None:
        base = {
            "run_id": "test",
            "task_id": "worker",
            "repository": "owner/repo",
            "worktree": "/tmp/worktree",
            "integration_branch": "factory/test",
            "target_branch": "main",
            "working_branch": "factory/test/worker",
            "paths": ["docs/worker"],
            "instruction": "Work",
        }
        with self.assertRaisesRegex(ValueError, "paths must be an array"):
            ProviderTaskRequest.from_mapping({**base, "paths": "docs/worker"})
        with self.assertRaisesRegex(ValueError, "remote"):
            ProviderTaskRequest.from_mapping({**base, "remote": "https://evil.example"})

    def test_healthy_remote_provider_beats_degraded_zero_cost_provider(self) -> None:
        item = WorkItem(
            task_id="task",
            title="Task",
            role="implementation",
            paths=("src/task",),
            required_capabilities=frozenset({"reasoning", "repo_read", "repo_write"}),
        )
        selection = select_runtime_provider(
            item,
            available_provider_ids=["opencode_ollama", "jules", "codex"],
            health={
                "opencode_ollama": ProviderHealth("opencode_ollama", "degraded", "slow"),
                "jules": ProviderHealth("jules", "healthy", "ready"),
                "codex": ProviderHealth("codex", "healthy", "manual only"),
            },
            allow_metered=True,
        )
        self.assertEqual(selection.provider_id, "jules")
        self.assertNotIn("codex", selection.considered)

    def test_telemetry_redacts_secret_values_and_token_shapes(self) -> None:
        event = TelemetryEvent(
            "run",
            "task",
            "jules",
            "provider",
            "failed",
            "token=abc123 password: xyz github_pat_abcdefghijklmnopqrstuvwxyz123456",
        )
        payload = event.to_json_line()
        self.assertNotIn("abc123", payload)
        self.assertNotIn("xyz", payload)
        self.assertNotIn("github_pat_", payload)
        self.assertIn("<redacted>", payload)

    def test_local_provider_completion_is_committed_and_pushed_to_worker_branch(self) -> None:
        with tempfile.TemporaryDirectory(prefix="provider-runtime-") as raw:
            root = Path(raw)
            repo, bare = initialize_repository(root)
            subprocess.run(
                ["git", "-C", str(repo), "checkout", "-b", "factory/test/worker-a"],
                check=True,
                capture_output=True,
            )
            request = request_for(repo, "worker-a", "docs/worker-a")
            result = execute_provider_task(
                AntigravityAdapter(profile_home=root),
                request,
                runner=EditingRunner("docs/worker-a/result.md"),
                publish=True,
            )
            self.assertTrue(result.completed)
            self.assertEqual(result.evidence.changed_paths, ("docs/worker-a/result.md",))
            remote_sha = subprocess.run(
                [
                    "git",
                    "--git-dir",
                    str(bare),
                    "rev-parse",
                    "refs/heads/factory/test/worker-a",
                ],
                check=True,
                capture_output=True,
                text=True,
            ).stdout.strip()
            self.assertEqual(remote_sha, result.evidence.commit_sha)

    def test_out_of_scope_provider_change_is_rejected_before_publish(self) -> None:
        with tempfile.TemporaryDirectory(prefix="provider-runtime-scope-") as raw:
            root = Path(raw)
            repo, _ = initialize_repository(root)
            subprocess.run(
                ["git", "-C", str(repo), "checkout", "-b", "factory/test/worker-b"],
                check=True,
                capture_output=True,
            )
            request = request_for(repo, "worker-b", "docs/worker-b")
            with self.assertRaisesRegex(ValueError, "protected path"):
                execute_provider_task(
                    AntigravityAdapter(profile_home=root),
                    request,
                    runner=EditingRunner(".github/workflows/escape.yml"),
                    publish=False,
                )

    def test_provider_cannot_modify_git_config_hooks_or_remote(self) -> None:
        mutations = {
            "config": lambda repo: subprocess.run(
                ["git", "-C", str(repo), "config", "core.hooksPath", "malicious"],
                check=True,
            ),
            "hook": lambda repo: (
                (repo / ".git" / "hooks" / "pre-push").write_text(
                    "#!/bin/sh\nexit 1\n", encoding="utf-8"
                )
            ),
            "remote": lambda repo: subprocess.run(
                [
                    "git",
                    "-C",
                    str(repo),
                    "remote",
                    "set-url",
                    "origin",
                    "https://evil.example/repo.git",
                ],
                check=True,
            ),
        }
        for name, mutation in mutations.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory(
                prefix=f"provider-runtime-{name}-"
            ) as raw:
                root = Path(raw)
                repo, _ = initialize_repository(root)
                branch = f"factory/test/worker-{name}"
                subprocess.run(
                    ["git", "-C", str(repo), "checkout", "-b", branch],
                    check=True,
                    capture_output=True,
                )
                request = request_for(repo, f"worker-{name}", f"docs/worker-{name}")
                with self.assertRaisesRegex(ValueError, "Git|remote"):
                    execute_provider_task(
                        AntigravityAdapter(profile_home=root),
                        request,
                        runner=EditingRunner(
                            f"docs/worker-{name}/result.md", git_mutation=mutation
                        ),
                        publish=False,
                    )

    def test_provider_cannot_move_non_worker_refs(self) -> None:
        with tempfile.TemporaryDirectory(prefix="provider-runtime-ref-") as raw:
            root = Path(raw)
            repo, _ = initialize_repository(root)
            subprocess.run(
                ["git", "-C", str(repo), "checkout", "-b", "factory/test/worker-ref"],
                check=True,
                capture_output=True,
            )
            seed = repo / "docs" / "worker-ref" / "seed.md"
            seed.parent.mkdir(parents=True, exist_ok=True)
            seed.write_text("seed\n", encoding="utf-8")
            subprocess.run(["git", "-C", str(repo), "add", "docs/worker-ref/seed.md"], check=True)
            subprocess.run(
                ["git", "-C", str(repo), "commit", "-m", "worker seed"],
                check=True,
                capture_output=True,
            )
            request = request_for(repo, "worker-ref", "docs/worker-ref")

            def move_main(worktree: Path) -> None:
                subprocess.run(
                    ["git", "-C", str(worktree), "update-ref", "refs/heads/main", "HEAD"],
                    check=True,
                )

            with self.assertRaisesRegex(ValueError, "refs outside"):
                execute_provider_task(
                    AntigravityAdapter(profile_home=root),
                    request,
                    runner=EditingRunner(
                        "docs/worker-ref/result.md", git_mutation=move_main
                    ),
                    publish=False,
                )


if __name__ == "__main__":
    unittest.main()
